// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN5oWWJm6An5RMOlpnFndqr4JSXdVQD48',
    appId: '1:512116143378:web:8cd3d05584fcb9a8bfafcb',
    messagingSenderId: '512116143378',
    projectId: 'futter-encrypted-chating-app',
    authDomain: 'futter-encrypted-chating-app.firebaseapp.com',
    storageBucket: 'futter-encrypted-chating-app.appspot.com',
    measurementId: 'G-E4S3XCXHDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2NGF3vkarWQP00Gklmf6ULrH3mPE1398',
    appId: '1:512116143378:android:3cb684e0e7dfcbbabfafcb',
    messagingSenderId: '512116143378',
    projectId: 'futter-encrypted-chating-app',
    storageBucket: 'futter-encrypted-chating-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNC9C-f_KyA2d4IvckXQyOcQ8F9E53cjw',
    appId: '1:512116143378:ios:e50ff94055594351bfafcb',
    messagingSenderId: '512116143378',
    projectId: 'futter-encrypted-chating-app',
    storageBucket: 'futter-encrypted-chating-app.appspot.com',
    iosBundleId: 'com.example.flutterEcryptedNewchatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNC9C-f_KyA2d4IvckXQyOcQ8F9E53cjw',
    appId: '1:512116143378:ios:e50ff94055594351bfafcb',
    messagingSenderId: '512116143378',
    projectId: 'futter-encrypted-chating-app',
    storageBucket: 'futter-encrypted-chating-app.appspot.com',
    iosBundleId: 'com.example.flutterEcryptedNewchatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN5oWWJm6An5RMOlpnFndqr4JSXdVQD48',
    appId: '1:512116143378:web:e5159ad142d0e21cbfafcb',
    messagingSenderId: '512116143378',
    projectId: 'futter-encrypted-chating-app',
    authDomain: 'futter-encrypted-chating-app.firebaseapp.com',
    storageBucket: 'futter-encrypted-chating-app.appspot.com',
    measurementId: 'G-Z4V31YDQEN',
  );
}
